#!/bin/python3

#Variables and Methods

quote = "I cannot believe I am learning how to hack!"

print(quote)


print(quote.upper()) #uppercase
print(quote.lower()) #lowercase
print(quote.title()) #title case

print(len(quote))

name = "Raffaellooo" #string
age = 31 #int int(30)
gpa = 3.3 #float  


print(int(age))
print(int(31.3))

print("My name is " + name + " and I am " + str(age) + " years old.")

age += 1 
print (age)

birthday = 1 
age += birthday 
print(age)

print('\n')
#functions
print("Here is an example of a function:")

def who_am_i():	
	name ="Raffaellooo"
	age = "31"
	print("My name is " + name + " and I am " + str(age) + " years old.")


who_am_i()

#adding parameters
def add_one_hundred(num):
	print(num + 100)
	
add_one_hundred(100)

#multiple parameters
def add(x,y):
	print(x+y)
	
add(7,7)

def multiply(x,y):
	return x * y
	
print (multiply(7,7))

def square_root(x):
	print(x ** .5)
	
square_root(64)

def nl():
	print('\n')

nl()

#boolean expressions (True or False)
print ("Boolean expressions:")

bool1 = True
bool2 = 3*3 == 9
bool3 = False
bool4 = 3*3 != 9

print (bool1, bool2, bool3, bool4)
print (type(bool1))

nl()
#relation and Boolean operators
greater_than = 7 > 5 
less_than = 5 < 7
greater_than_equal_to = 7 >= 7
less_than_equal_to = 7 <=7 

test_and = (7 > 5) and (5 < 7) #True
test_and2 = (7 > 5) and (5 > 7) #False
test_or = (7 > 5) or (5 < 7) #True
test_or2 = (7 > 5) or (5 > 7) #True

test_not = not True #False 


nl()
#Condition Statements
def drink(money):
	if money >= 2:
		return "you've gots yaself a drink"
	else:
		return "No drinky drinky"
		
print(drink(3))		
print(drink(1))

def alcohol(age, money):
  if (age >=21) and (money >=5):
    return "we are getting a drink!"
  elif (age >= 21) and (money < 5):
    return "Come back with mo dollas"
  elif (age < 21) and (money >= 5):
    return "Nice try wise guy"
  else:
    return "you too poor and too young"

print(alcohol(21,5))
print(alcohol(21,4))	
print(alcohol(20,4))	

nl()
#Lists - Have brackets []
movies = ["When Harry Met Sally", "The Hangover", "The Perks of Being a Wallflower", "The Exorcist"]

print(movies[1])
print(movies[0])
print(movies[1:3])
print(movies[1:])
print(movies[:2])
print(movies[-1])

print(len(movies)) #adds
movies.append("JAWS")
print(movies)

movies.pop() #removes the very last item in the list
print(movies)

movies.pop(0) #you can choose what to remove as well
print(movies)

nl()
#Tuples - Do not change, ()
grades = ("a","b","c","d","f")
print(grades[1])

nl()
#Looping

#For loops - start to finish of an iterate
vegetables = ["cucumber","spinach","cabbage"]
for x in vegetables:
	print(x)
	
#While loops - Execute as long as true
i = 1

while i < 10:
	print (i)
	i += 1
	
